---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: authelia-user-password-db
  namespace: authelia
spec:
  encryptedData:
    password: AgBsi89osLIoaPqeyXt4mN4pd3je88KS17jx9jMkAXkMOjVB5dNhNAdu1hKJTZ0h8kX+6chST+Y8yI6Bn+UGW0Lbci9r/KNslRi+16vze2qkbKB0HRccq01oZf5Jd0Eqky3V03K3fYNDKW2X22CMfVEp3PjQOO+Cfqm37wqbxTTcBSNMTGLq7LZvZ8N/2a18kOTQbcfxz6liXNOTEBddBhqUbq0UMHCHfMsaTZ8Ps/HkYrzAnjYitPwhDzJDAUnVDjUA2CrPy4o0P3Jn1WQlbrf2gGY10Mq7cVRQCBsLkwerDu5iT/j17uTYdzTBGST9/aKPCwMYJ2pzdmvar09li2er3SoT2TRgaU35lh9cxqZAYnBKHW+fd4y1vHdh2DgiU5io61wivalYQJuUjA/8Iz0y23Lj7kS1IEUxk/IeiGsEdk1lP4JEURbEHDEHvvElRn1KR4+78KOJOPH0wTi7k6hggEwyV8FJUE4IrtaT5J+tK+NAIFSoXjwhiHHpqDdoxU81CogjQVuZ7IedA+qUo6ofzwigM5KhuXSHzpUigXP/H31W+biTsQmEkLLai90x9TYHa0Ec9RYoeSXHWa7MQRaMLbRvk9LLihbuNdIbeOiYPSq6aZJtfkt83NAlgQY6VhJuT1f4haiVDnPgCh4doGXm7lGv4i3Udxcf/wciGnFigVZz8FA9bEsgVFu/P1g2RI6yCVk5LKSZ3WrnMdYT
    username: AgByuok/8+YNvDqFk3UWfrE6MRYHlMW9EQucNBqmuYBB8Xuw6xccBthV8iIXjYgNc45hog0jb3zZgiQAGCJUuWBS4WoJlNMJLDFed9uymmsoCcD0HQHHTnX86LuauwbPAM5mfOBS4K1cMQFrIvzY5T/CG25lGLFMyTFKcNhsG8rprkWdbXlrwH0xKsDZ9635yRYagm1l0uMng5yQ5C1k7YZ4nvzp3vQM1GkZ2sFVrboxee1OibHeDVwcsJC8W1HXVJ0lnB7+I+IijavE/AhX3nFRXzGh8XChZry7iOCXfz+asBGVvTj8vg/u1pQq8/JntD3+PnoHv3xhyPNoPbdi+z7ADbY+7PGWHQVTnNobciTM0GjUlnCrT5c3jYk+QbKlhH73R5uhGLeXRgXOxIH1vP806edXnw95RKPBxk+p4mnjy9wZyfY37/MsI/m81Xfk9vYQNTOwIKAxrXEMjPum5WBOJO8Ez8A9UWaMg1iOjhI6+CAUbJZ97xBnRwWKNAo6wXR0tjmEWgbzVggDGzX5bMSJ5dH/OGeZTTvuZMFEs+/w6sGVgpjTXAhrcUBQFBUVNUDRtjVB9SFSsPtFyJZJqta6NfLMOSRbHTy/BuRzN0G76hcbI0VHQS/5KarOGoEaPrckj4vQALemSCoYLETShT2mFF5t14bOWgw+la2x5Nhls81jRNeGhLlmwsoi8fNJNMSyRC20ip4cwg9IG9c8
  template:
    metadata:
      creationTimestamp: null
      name: authelia-user-password-db
      namespace: authelia
    type: kubernetes.io/basic-auth
