---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: authelia-user-password
  namespace: database
spec:
  encryptedData:
    password: AgCZ1VLhFdCjARsA4kzULwdFrAddLGaFtT2NBfxbchRwLz4xgqfa5hyuEr94ONI07nGdfgS+fcZ06WfCsJ/RxC0nI+34D1tPZXUUTdAxARWUrI7G0GRR4HO9kuZioU3ay7il8UKVA6Q1P/0OsaQ9/7CKJAJmCFh3I886WPPExi/6cfrnSJTVWT9OxcGHdih5NVWlt9iTPsbnlS8RPslJGGY9T7ZOuQUIA6VRE2QG3EJr5GRc1CSYSmzkLwB7xeN7gSBGBhp47E8aM27TG+RIdegDEA12S9myF+ryyyax1PzWFD7rtnOV6IjN9tn8ypDKydCzHJ4iFujEZK5WskHQPqqcckgQFZWEn1mjMkn/sjt1aiEugWsXodJtAzcJwEEpKiemAMfDQMRBAPZCurF2V3z0iksPRSVm4/VHPQkvlyEQe+HUm2TOukVOgnhpUOY3fBzNs+Of0NVoS6Hil9H+T4gYZxn7PKGOpU7p2qYf+EmGWUkZ7QSvoRlMYHi3bifxhzD2FdCiJj8oPRyJ+Nb41OA7kK+ZkJCLIvu4nC7PNqoRbkstzpDT3ROr6MGhkDyYNuxYDwxKGsm83NAN6rz36xApaIYEVX7H1K1+jkAO4gcorSX/hj5m2ouy/N67i3MxGnDBQ3j1J/AJyvBRv0npNd65YdJRX+ZAXu0IkoR0bixqo5EIFhtaNYqC6Rst5sng9Yd6w4cIJWhCUMwz/ebi
    username: AgA7SBqqjdzbA9bsPoHu/oPdFMRzIXKb9nxLE94Bl7uRdnO3ayw3aYBcjCt7j2VB5wp9rYnohcTMJGgeVfjC5c+tVrbWm/VyyzOK1TXgFip8BE4eMjPfv9FRVx/3uQqlHYHR/uWTAVJNdSoVKO2FVwWpWyeGwldgkVfK4POekWYICFbQYCcAfDJsfP4r3pADYWzLFAOHNtZNGQaL4aJ8Phldlo7isRX9sJ6sskLyhK+PXqxDfy+/O1AfQzbM7L0mB0/I+YA5xOClovrNXLYUw2mCugnPqgsR3CkPyPx0+Uza45fgiF1ZhsxaLWl3xclcRLmhn1zbgSA1EpEVqcYr/YmKjUbzm7ktEDwmthYEq5crQqsNqjLEzzR5UrmC01/pTzLf5lLe/hu8FAy07b9MIaDqGzMVHgj4lSdfMVL1DKKnR564WieHfdBPURBCFVgYtHUMmgKsswW9h/lr5OcXReKLrDlNJQYYRFJlI30Dl1SaIFjv3i0T0sxcqpr0gpJeOlZVG8C1QKwW2iel9G0sMtHGLy2JrX7bag2H7E7z/5qTHszcEuFR4MOEtPMNOckaY7iNybCxkQP7XyshlPUyIOHRgWPCAWBKmS8KTenuGFbgJAcNZaFbHymFcyoG2HMDaO4jX5RFNDoH5Jj64iuUoHTPnzMhIkAv33xMA0A9u0V/hemJMW2RQuaaGeqXEOqwD5y0RnZkfP9Q21zIl2rj
  template:
    metadata:
      creationTimestamp: null
      name: authelia-user-password
      namespace: database
    type: kubernetes.io/basic-auth
