# apps/authelia/values.yaml

configMap:
  theme: dark

  server:
    path: "auth"

  session:
    cookies:
      - domain: k3s-control-plane-1.tail783ccb.ts.net
        default_redirection_url: https://auth.k3s-control-plane-1.tail783ccb.ts.net/auth

  storage:
    local:
      path: /config/db.sqlite

  notifier:
    filesystem:
      filename: /config/notification.txt

  authentication_backend:
    file:
      path: /secrets/users_database.yml

secret:
  existingSecret: "authelia-secrets"