apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-ingress
  namespace: argocd
  annotations:
    kubernetes.io/ingress.class: traefik
    # Evita quedas de conexão na interface web do ArgoCD
    traefik.ingress.kubernetes.io/router.protocols: h2c
spec:
  ingressClassName: traefik
  rules:
    - host: k3s-control-plane-1.tail783ccb.ts.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  number: 80
