configs:
  cm:
    url: http://k3s-control-plane-1.tail783ccb.ts.net
    admin.enabled: true
    dex.config: |
      connectors:
        - type: github
          id: github
          name: GitHub
          config:
            clientID: ${github_client_id}
            clientSecret: ${github_client_secret}
  rbac:
    scopes: '[groups, email]'
    policy.default: role:readonly
    policy.csv: |
      g, ${github_admin_user}, role:admin
      g, "felipevarejao@users.noreply.github.com", role:admin
